language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: sesion6-travis-heroku
  on: master
  skip_cleanup: true
  api_key:
    secure: TzI2rSDLwOBeteKeFCAPPRtT8FrngUc0eNf2vWXo3ZqjMgmbpl9ps5rCi9S16GSuPuTs4a3yP/Mt4sZyIhncnvWBFAD170l9BMTQGlJkVB8mwMZt2qTyJ3sok/NRuE7lfzvrgzVU/vVpuQcmUlq382k2bsOfaygpJUWVMpZS3zsm8mhuDdMzG5q5+gAGIQTC/Qebx7HBCZS61AVzGBtLX2P9mWV8i6eJ0bu1laJA2JhyMQsTHLl/l1bLoib/ZZAlJq0zFt7Nt0oxL8HBxZMH+MzMGpQX6HFvyNaQ4v4FF9Rvzu6rchMVXHmqZOrgJGxig3MpWpq/DomSd38U5/3RSdwtSFlhSXGJR7o+kykeDBpK7P7fTe2lbl1n1jpbZdXWK2ffGZ2lzA6jlLM4QRBTUd0/9sptCXWVVslR+AX+/Mvg6AlFqjk/vswxd/1i/8XtvLH0W+ARVxzjsq7hIY8jm9CfsNWcu0Tim41rLJiFkgoqXbvw4xBuJJ8nvzMMrn9Px3K0AqGDnGZJtdxCjsni+FrFDVxpe/ybn7f4lbeWOvQ2nop0ULiRhsRwQABUg+jVRvaOF2yKWZa9IDoqdYtws0caCJQQkwoWOYeYySZbUf5EioNQR1O25Yi+Ux8oB0HcqdssbHtUzVbvA4bA9bCn78XpsdD0M+e5s+1N1sur3K4=
